# node1.toml
[server]
port = 5555

[node]
detect-drivers = true

[relay]
url = "http://localhost:4723"
status-endpoint = "/status"
configs =[
"2", "{\"platformName\": \"Android\", \"appium:platformVersion\": \"14.0\", \"appium:deviceName\": \"emulator-5554\", \"appium:automationName\": \"UiAutomator2\"}"
]